{{- $service := .Values.service | default (dict) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apiserver.fullname" . }}
  labels:
    {{- include "apiserver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ default 8000 $service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "apiserver.selectorLabels" . | nindent 4 }}
