apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.fullname" . }}-master
  labels:
    {{- include "spark.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "spark.name" . }}
    app.kubernetes.io/component: master
  ports:
    - name: rpc
      port: {{ .Values.master.rpcPort }}
      targetPort: rpc
    - name: web
      port: {{ .Values.master.webPort }}
      targetPort: web
