{{- $gateway := .Values.dagsterGateway -}}
{{- if and $gateway ($gateway.enabled | default true) }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $gateway.name }}
spec:
  gatewayClassName: {{ $gateway.gatewayClassName }}
  listeners:
{{- range $gateway.listeners }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
{{- with .hostname }}
      hostname: {{ . }}
{{- end }}
{{- with .tls }}
      tls:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .allowedRoutes }}
      allowedRoutes:
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
{{- end }}
