{{- with .Values.mongodbGateway }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .name }}
spec:
  gatewayClassName: {{ .gatewayClassName }}
  listeners:
{{- range .listeners }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
{{- with .hostname }}
      hostname: {{ . }}
{{- end }}
{{- with .allowedRoutes }}
      allowedRoutes:
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
{{- end }}
