apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-creds
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
data:
  MINIO_ROOT_USER: {{ .Values.accessKey | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secretKey | quote }}
