{{- $secrets := .Values.secrets | default (dict) -}}
{{- $data := $secrets.data | default (dict) -}}
{{- if $secrets.create | default true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dagster.fullname" . }}-env
  labels:
    {{- include "dagster.labels" . | nindent 4 }}
type: Opaque
data:
  MINIO_ACCESS_KEY: {{ required "secrets.data.MINIO_ACCESS_KEY is required" $data.MINIO_ACCESS_KEY }}
  MINIO_SECRET_KEY: {{ required "secrets.data.MINIO_SECRET_KEY is required" $data.MINIO_SECRET_KEY }}
  UPLOADS_MONGODB_URI: {{ required "secrets.data.UPLOADS_MONGODB_URI is required" $data.UPLOADS_MONGODB_URI }}
{{- end }}
